[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-msgspec-openapi"
version = "0.1.1"
description = "FastAPI plugin for automatic OpenAPI schema generation from msgspec structs"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "RamsesDev", email = "nullint95@gmail.com" }
]
requires-python = ">=3.10"
keywords = [
    "fastapi",
    "msgspec",
    "openapi",
    "typescript",
    "api",
    "serialization",
    "validation",
    "swagger",
    "documentation"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: FastAPI",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Typing :: Typed",
]
dependencies = [
    "fastapi>=0.100.0",
    "msgspec>=0.18.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.24.0",
]

[project.urls]
Homepage = "https://github.com/S3wnkin/fastapi-msgspec-openapi"
Documentation = "https://github.com/S3wnkin/fastapi-msgspec-openapi#readme"
Repository = "https://github.com/S3wnkin/fastapi-msgspec-openapi"
Issues = "https://github.com/S3wnkin/fastapi-msgspec-openapi/issues"

[tool.hatch.build.targets.wheel]
packages = ["fastapi_msgspec_openapi"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long (handled by formatter)
]

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = [
    "tests/",
    "test_.*\\.py$",
]